name: Add Update Label Weekly

on:
  schedule:
    - cron: '0 7 * 1-6,8-11 5'
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (will not post comments or update issues)'
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'

permissions:
  contents: read
  issues: read

jobs:
  Check-issues-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: t-will-gillis/maintenance-actions/add-update-label-weekly@v0.4.3
        with:
          github-token: ${{ secrets.UPDATE_LABEL }}
