name: Add Update Label Weekly

on:
  schedule:
    - cron: '0 7 * 1-6,8-11 5'
  workflow_dispatch:

permissions:
  contents: read
  issues: read

jobs:
  check-staleness:
    runs-on: ubuntu-latest
    steps:
      - uses: t-will-gillis/maintenance-actions/add-update-label-weekly@main
        with:
          github-token: ${{ secrets.MY_TOKEN }}