name: Add Update Label Weekly

on:
  schedule:
    - cron: '0 7 * 1-6,8-11 5'
  workflow_dispatch:

permissions:
  contents: read
  issues: read

jobs:
  Check-issues-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: t-will-gillis/maintenance-actions/add-update-label-weekly@v0.3.1
        with:
          github-token: ${{ secrets.UPDATE_LABEL }}
